DROP SCHEMA IF EXISTS dds CASCADE;
DROP SCHEMA IF EXISTS datamart CASCADE;
DROP SCHEMA IF EXISTS damaged_data CASCADE;      
CREATE SCHEMA IF NOT EXISTS dds;
CREATE SCHEMA IF NOT EXISTS datamart;
CREATE SCHEMA IF NOT EXISTS damaged_data;